#!/bin/bash

mkdir ./include

git clone https://github.com/LouisRoss/spiking-model-core.git
mkdir spiking-model/include/core
cp -rf spiking-model-core/include/* spiking-model/include/core
cp -R spiking-model-core/ui spiking-model/
cp -R spiking-model-core/config spiking-model/
rm -rf spiking-model-core/*
rm -rf spiking-model-core/\.*
rmdir spiking-model-core

git clone https://github.com/LouisRoss/modelengine.git
cp -r modelengine/include/* ./include
rm -rf modelengine/*
rm -rf modelengine/\.*
rmdir modelengine

git clone https://github.com/BlueBrain/HighFive.git
cp -r HighFive/include/* ./include
rm -rf HighFive/*
rm -rf HighFive/\.*
rmdir HighFive

git clone https://github.com/vincentlaucsb/csv-parser.git
mkdir ./include/csv-parser
cp -r csv-parser/single_include/* ./include/csv-parser
rm -rf csv-parser/*
rm -rf csv-parser/\.*
rmdir csv-parser
