#!/bin/bash

# spiking-model can read from HDF5 neural models, we need the library and include files.
unzip -q bmtk.zip
mkdir /bmtk
mv bmtk/ /bmtk/Chapter04

# We need the public API for HighFive as well as the private one.
apt-get update
apt-get install -y libhdf5-serial-dev
