BDIR=../bin

all: $(BDIR)/mes.py $(BDIR)/mem.py $(BDIR)/mev.py $(BDIR)/mec.py $(BDIR)/np.py $(BDIR)/nn.py $(BDIR)/nnclean.py $(BDIR)/nnplot.py $(BDIR)/nntidy.py
.PHONY: all

$(BDIR)/mes.py: mes.py
	cp mes.py $(BDIR)/

$(BDIR)/mem.py: mem.py
	cp mem.py $(BDIR)/

$(BDIR)/mev.py: mev.py
	cp mev.py $(BDIR)/

$(BDIR)/mec.py: mec.py
	cp mec.py $(BDIR)/

$(BDIR)/np.py: np.py
	cp np.py $(BDIR)/

$(BDIR)/nn.py: nn.py
	cp nn.py $(BDIR)/

$(BDIR)/nnclean.py: nnclean.py
	cp nnclean.py $(BDIR)/

$(BDIR)/nnplot.py: nnplot.py
	cp nnplot.py $(BDIR)/

$(BDIR)/nntidy.py: nntidy.py
	cp nntidy.py $(BDIR)/

