BDIR=../bin

all: $(BDIR)/mes.py $(BDIR)/mem.py $(BDIR)/mev.py $(BDIR)/mec.py $(BDIR)/np.py
.PHONY: all

$(BDIR)/mes.py: mes.py
	cp mes.py $(BDIR)/

$(BDIR)/mem.py: mem.py
	cp mem.py $(BDIR)/

$(BDIR)/mev.py: mev.py
	cp mev.py $(BDIR)/

$(BDIR)/mec.py: mec.py
	cp mec.py $(BDIR)/

$(BDIR)/np.py: np.py
	cp np.py $(BDIR)/

